package main

import (
	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/noo-dev/pet_chat/internal/config"
	"github.com/noo-dev/pet_chat/internal/ports/http/server"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	godotenv.Load()
}

// @title Chat Service
// @version 0.0.1
// @description Service for handling messages and websockets Chat microservice
// @termsOfService http://swagger.io/terms/

// @host localhost:8081
// @BasePath /v2
func main() {
	e := echo.New()
	cfg := config.Load()

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.GET("/", func(ctx echo.Context) error {
		return ctx.String(200, "Hello microservices")
	})

	srv := server.NewServer(cfg.HttpServer, nil, e)

	srv.Start()
}
